### ISSUE TITLE
Add CSV file with plant characteristics that PG doesn't include yet

### ISSUE THREAD

**Issue by gschivley** [gschivley/PowerGenome#24]
This includes things like `Eff_up`, `Eff_down`, `Ramp_Up_percentage`, `Ramp_Dn_percentage`, etc. Things that are needed for all current resources and are currently copied in by hand.

@chuanzhang1990 are you still willing to take care of this? It would also be great if you try adding the code to incorporate the values.

Things that will need to be done:
- Create CSV. Use EIA technology names and the ATB combination of <technology>_<tech_detail>.
- Add CSV to a subfolder under `powergenome/data`.
- Add subfolder path to the `DATA_PATHS` dictionary in `params.py`, following the example of `DATA_PATHS["additional_techs"]`.
- Add a parameter to the settings file that specifies the filename so users can change it if they want.
- Add a method to the `GeneratorClusters` class that will read the CSV and merge the values into the dataframe of all generators.

**Comment by chuanzhang1990** [comment]
@gschivley Yes, I can spend some time doing this, but I think I might need many help from you, I have not done such stuff for a long time

**Comment by zaneselvans** [comment]
Hah, you have a variable named `Eff_up`?

I don't know if this would be useful/relevant for your purposes, but we've been talking about trying to infer or constrain ramp rates, excess fuel consumption associated with generator startup, and minimum operating capacity for units based on EPA CEMS time series. And ultimately trying to model the fixed costs associated with each startup event -- as stuff that would come after our Sloan grant is done.

**Comment by gschivley** [comment]
Hey @zaneselvans I missed your comment on this. Yes, those operational parameters are all things that we need better data on. There are reasonable references for startup fuel use and costs from NREL but they are from 2012. Time to start would be the most helpful in the short term.

**Comment by gschivley** [comment]
We now have an external file where this stuff can be specified.
