### ISSUE TITLE
Time clustering error with 16 weeks

### ISSUE THREAD

**Issue by gschivley** [gschivley/PowerGenome#40]
When using 16 periods of 7 days, the [time clustering function](https://github.com/gschivley/PowerGenome/blob/831827dcde8af066724cba2fea045f571514877e/powergenome/time_reduction.py#L9) returns a blank line (nans) for both load and resource variability. I haven't been able to duplicate the behavior with any other combination of periods/days.

**Comment by gschivley** [comment]
@nspatank did you ever fix this?

**Comment by nspatank** [comment]
yes, we need to add `input_data = input_data.reset_index()`  after this: `input_data = pd.concat([load_profiles, resource_profiles], axis=1)`

**Comment by gschivley** [comment]
Fixed in PR #43 and #45
