### ISSUE TITLE
ClusterBuilder in params breaks tests

### ISSUE THREAD

**Issue by gschivley** [gschivley/PowerGenome#52]
@ezwelty this line

```
CLUSTER_BUILDER = ClusterBuilder.from_json(
    Path(SETTINGS["RESOURCE_GROUPS"]).glob("**/*.json")
)
```
breaks the tests because it doesn't have a .env file. Any idea how to fix?

**Comment by ezwelty** [comment]
@gschivley Two options I see:

- Create a `.env` file for the test suite and include one or more (synthetic or real) resource groups in testing.
- If no `.env` file or no `SETTINGS["RESOURCE_GROUPS"]`, create an empty ClusterBuilder: `CLUSTER_BUILDER = ClusterBuilder([])`.
