### ISSUE TITLE
Issue with Network.csv generated from PowerGenome run

### ISSUE THREAD

**Issue by sambuddhac** [gschivley/PowerGenome#73]
The sequence of rows that's desired: 

Region description | Network_zones | DistrZones | CES | RPS | CO_2_Max_Mtons | CO_2_Max_ton_MWh | CO_2_Import_ton_MWh | CO_2_Export_ton_MWh | Network_lines | z1 | Line_Max_Flow_MW | Line_Min_Flow_MW | Transmission Path Name | distance_mile | Line_Loss_Percentage | Line_Max_Reinforcement_MW | Line_Reinforcement_Cost_per_MW_yr
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

The sequence of rows generated currently:

Region description | Network_zones | DistrZones | CES | RPS | CO_2_Max_Mtons | CO_2_Max_ton_MWh | CO_2_Import_ton_MWh | CO_2_Export_ton_MWh | Network_lines | USA_Single | Line_Max_Flow_MW | Line_Min_Flow_MW | Transmission Path Name | distance_mile | Line_Loss_Percentage | Line_Max_Reinforcement_MW | Line_Reinforcement_Cost_per_MW_yr
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

So, there's a z1 column missing in between "Network_lines" and "Line_Max_Flow_MW" and instead the current version produces the name of the model region.

**Comment by gschivley** [comment]
Hi @sambuddhac, sorry that I missed this! Fixed with c7a39c67594be8bfbb958bae4d8ec42efedfbdf2

**Comment by sambuddhac** [comment]
Thanks Greg !!! Much appreciated.
