### ISSUE TITLE
about region aggregation

### ISSUE THREAD

**Issue by nspatank** [gschivley/PowerGenome#82]
atb2020 branch is throwing an error if we don't specify the `region_aggregations` flag or if the flag is empty. We should be able to specify IPM regions directly as model regions without having to specify any aggregation

**Comment by gschivley** [comment]
Good to know, I'll take a look this afternoon.

**Comment by nspatank** [comment]
I found the fix. We need to add the following line in util.py on line 60
`if settings.get("region_aggregations") is not None:`

**Comment by gschivley** [comment]
Fixed in 1cdb7557ae4bff5cb067281cd4722734fb6ca355
